# -*- coding: utf-8 -*-
"""anomaly_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19OOgMVVtw9C4TpAsnhH-QldoZmpQsn8E
"""

from scipy.stats import skewnorm
import matplotlib.pyplot as plt
import numpy as np

numValues = 10000
maxValue = 100
skewness = 20

random = skewnorm.rvs(a = skewness, loc = maxValue, size = numValues)
random = random - min(random)
random = random / max(random)
random = random * maxValue

x = random

plt.hist(x, bins = 50)

plt.hist(x**0.5, bins = 50)

plt.hist(np.log(x+1), bins = 50)

plt.hist(x**2, bins = 50)

