# -*- coding: utf-8 -*-
"""Practicing_Plotting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xIsqGs8gxxfDDCMsTgS_vFQbcLDW6oYO
"""

import matplotlib.pyplot as plt

plt.plot([2,4,6.3,8])
plt.ylabel("Numbers")
plt.xlabel("Indices")
plt.show()

plt.plot([2,4,6.3,8])
plt.ylabel("Numbers")
plt.xlabel("Indices")
plt.grid()
plt.show()

plt.plot([1,2,3,4],[1,4,6,8])
plt.xlabel("Numbers")
plt.ylabel("Twice")
plt.title("Number Table")
plt.grid()
plt.show()

plt.plot([1,2,3,4],[1,4,6,8], 'ro')
plt.grid()
plt.show()

x_values = [1,2,3,4]
plt.plot(x_values, [2*val for val in x_values], 'b--', label='2X')
plt.plot(x_values, [3*val for val in x_values], 'rs', label='3X')
plt.plot(x_values, [4*val for val in x_values], 'g^', label='4X')

plt.grid()
plt.legend()
plt.show()

plt.plot([1,2,3,4],[1,4,9,16],linewidth = 5.0)
plt.show()

x1 = [1,2,3,4]
y1 = [1,4,9,16]
x2 = [1,2,3,4]
y2 = [2,4,6,8]
lines = plt.plot(x1,y1,x2,y2)

plt.setp(lines[0],color = 'r',linewidth =2.0)

plt.setp(lines[1],color  = 'g',linewidth =2.0)
plt.grid()

plt.figure(1)
plt.subplot(211)
plt.plot([1,2,3])
plt.subplot(212)
plt.plot([4,5,6])
plt.figure(1)
plt.subplot(211)
plt.title('Basic Plots')
plt.figure(2)
plt.plot([4,5,6])

# plt.figure(1)
# plt.subplot(211)
# plt.title('Basic Plots')
plt.show()

